{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crm-backend.serviceAccountName" . }}
  namespace: {{ include "crm-backend.namespace" . }}
  labels:
    chart: {{ include "crm-backend.chart" . }}
    release: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
