apiVersion: v2
name: crm-frontend
description: Helm chart for CRM Frontend Applications
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - crm
  - frontend
  - react
maintainers:
  - name: CRM Team
    email: crm@example.com
